### ISSUE TITLE
Problem with load

### ISSUE THREAD

**Issue by jhdscript** [stevesoltys/grooveshark-android#1]
hello,

http://grooveshark.com/preload.php?getCommunicationToken=1&hash=%2F dont seems to work anymore

Could you help me please

**Comment by stevesoltys** [comment]
Hi,

Can you explain exactly what isn't working? That link is still producing the results that it did before. I tested the API and it is still working correctly on my end. It is possible that Grooveshark has banned your IP.

Let me know if that is the case, or if it is something else.

**Comment by stevesoltys** [comment]
I assume this is the same issue as #2. If so, please see my example there. If that was not the case feel free to re-open this issue.
